$(document).ready(function() {
    //changing dropdown dynamically
    $("#userCountry").change(function(){
        var userCountry = $("#userCountry").val();

        if(userCountry != ""){
            $("#userCountry").find('#defaultUserCountry').remove();
        }

        if(userCountry == "Austria") {
            var temp = new Array("Vienna",
            "Graz",
            "Linz",
            "Salzburg",
            "Innsbruck",
            "Klagenfurt",
            "Wels",
            "Dornbirn",
            "Wiener Neustadt",
            "Steyr",
            "Bregenz",
            "Leonding",
            "Klosterneuburg",
            "Wolfsberg",
            "Leoben",
            "Krems an der Donau",
            "Traun",
            "Amstetten",
            "Lustenau",
            "Kapfenberg",
            "Hallein",
            "Mödling",
            "Kufstein",
            "Traiskirchen",
            "Schwechat",
            "Braunau am Inn",
            "Stockerau",
            "Saalfelden am Steinernen Meer",
            "Hohenems",
            "Ansfelden",
            "Bruck an der Mur",
            "Telfs",
            "Spittal an der Drau",
            "Perchtoldsdorf",
            "Ternitz",
            "Bludenz",
            "Eisenstadt",
            "Feldkirchen",
            "Bad Ischl",
            "Hall in Tirol",
            "Wörgl",
            "Schwaz",
            "Marchtrenk",
            "Hard",
            "Feldbach",
            "Gmunden",
            "Korneuburg",
            "Neunkirchen",
            "Knittelfeld",
            "Sankt Veit an der Glan");

            var userCity = temp.sort();
        } else if(userCountry == "Canada") {
            var temp = new Array("Toronto",
            "Montréal",
            "Vancouver",
            "Calgary",
            "Edmonton",
            "Ottawa",
            "Mississauga",
            "Winnipeg",
            "Quebec City",
            "Hamilton",
            "Brampton",
            "Surrey",
            "Kitchener",
            "Laval",
            "Halifax",
            "London",
            "Victoria",
            "Markham",
            "St Catharines",
            "Niagara Falls",
            "Vaughan",
            "Gatineau",
            "Windsor",
            "Saskatoon",
            "Longueuil",
            "Burnaby",
            "Regina",
            "Richmond",
            "Richmond Hill",
            "Oakville",
            "Burlington",
            "Barrie",
            "Oshawa",
            "Sherbrooke",
            "Saguenay",
            "Lévis",
            "Kelowna",
            "Abbotsford",
            "Coquitlam",
            "TroisRivières",
            "Guelph",
            "Cambridge",
            "Whitby",
            "Ajax",
            "Langley",
            "Saanich",
            "Terrebonne",
            "Milton",
            "St Johns",
            "Moncton");

            var userCity = temp.sort();
        } else if(userCountry == "China") {
            var temp = new Array("Shanghai",
            "Guangzhou",
            "Beijing",
            "Shenzhen",
            "Nanyang",
            "Baoding",
            "Chengdu",
            "Linyi",
            "Tianjin",
            "Shijiazhuang",
            "Zhoukou",
            "Handan",
            "Weifang",
            "Wuhan",
            "Heze",
            "Ganzhou",
            "Tongshan",
            "Changsha",
            "Fuyang",
            "Jining",
            "Dongguan",
            "Jinan",
            "Foshan",
            "Chongqing",
            "Changchun",
            "Zhumadian",
            "Ningbo",
            "Cangzhou",
            "Nanjing",
            "Hefei",
            "Zhanjiang",
            "Shaoyang",
            "Hengyang",
            "Nantong",
            "Yancheng",
            "Nanning",
            "Xi’an",
            "Shenyang",
            "Tangshan",
            "Zhengzhou",
            "Shangqiu",
            "Yantai",
            "Xinyang",
            "Shangrao",
            "Luoyang",
            "Bijie",
            "Quanzhou",
            "Hangzhou",
            "Huanggang",
            "Maoming");

            var userCity = temp.sort();
        } else if(userCountry == "Croatia") {
            var temp = new Array("Zagreb",
            "Split",
            "Rijeka",
            "Osijek",
            "Zadar",
            "Velika Gorica",
            "Pula",
            "Slavonski Brod",
            "Karlovac",
            "Šibenik",
            "Kaštel Stari",
            "Dubrovnik",
            "Bjelovar",
            "Sisak",
            "Čakovec",
            "Vukovar",
            "Virovitica",
            "Samobor",
            "Vrbovec",
            "Ivanić-Grad",
            "Rovinj",
            "Trogir",
            "Županja",
            "Nova Gradiška",
            "Opatija",
            "Labin",
            "Križevci",
            "Crikvenica",
            "Knin",
            "Kastav",
            "Slatina",
            "Daruvar",
            "Čepin",
            "Bedekovčina",
            "Našice",
            "Poreč",
            "Križ",
            "Čavle",
            "Novska",
            "Ploče",
            "Belišće",
            "Krk",
            "Donji Miholjac",
            "Ivankovo",
            "Gospić",
            "Cestica",
            "Darda",
            "Buje",
            "Ilok",
            "Veliko Trgovišće");

            var userCity = temp.sort();
        } else if(userCountry == "Germany") {
            var temp = new Array("Berlin",
            "Hamburg",
            "Munich",
            "Cologne",
            "Frankfurt",
            "Bremen",
            "Düsseldorf",
            "Stuttgart",
            "Leipzig",
            "Dortmund",
            "Essen",
            "Dresden",
            "Hannover",
            "Nuremberg",
            "Duisburg",
            "Bochum",
            "Wuppertal",
            "Bielefeld",
            "Bonn",
            "Münster",
            "Karlsruhe",
            "Mannheim",
            "Augsburg",
            "Kassel",
            "Wiesbaden",
            "Mönchengladbach",
            "Gelsenkirchen",
            "Braunschweig",
            "Aachen",
            "Kiel",
            "Chemnitz",
            "Halle",
            "Magdeburg",
            "Freiburg im Breisgau",
            "Krefeld",
            "Mainz",
            "Lübeck",
            "Oberhausen",
            "Rostock",
            "Erfurt",
            "Hagen",
            "Potsdam",
            "Saarbrücken",
            "Hamm",
            "Ludwigshafen",
            "Mülheim",
            "Oldenburg",
            "Osnabrück",
            "Leverkusen",
            "Heidelberg");

            var userCity = temp.sort();
        } else if(userCountry == "Hong Kong SAR") {
            var temp = new Array("Hong Kong",
            "Sham Shui Po",
            "Sai Wan Ho",
            "Nga Ying Chau",
            "Pak Wan",
            "Tai Kok Tsui",
            "North Point Estate",
            "Aberdeen",
            "Shek Pai Wan Resettlement Estate",
            "Fung Wong Village",
            "Chuk Yuen",
            "Ma Tau Wai",
            "Ma Tau Kok",
            "Tin Shui Wai",
            "Sha Kong Wai Tsai",
            "Pak Kiu",
            "San Po Kong",
            "Nga Tsin Wai",
            "Tai Hom Village",
            "Wong Tai Sin",
            "Hung Hom",
            "Victoria",
            "Sai Ying Pun",
            "Ma Wan Tsuen",
            "Shau Kei Wan",
            "Tsin Shui Ma Tau",
            "Ham Tin",
            "Tai Lin Pai",
            "Mong Kok",
            "Shek Tong Tsui",
            "Yau Ma Hom",
            "Kwai Chung",
            "Ying Pun Ha",
            "Tai Po Kau Hui",
            "Ap Tsai Wan",
            "Ping Shek",
            "North Point",
            "Tsuen Wan",
            "Tai Uk Wai",
            "Wang Tau Hom",
            "Tai Wong Ha",
            "Sheung Ko Tan",
            "Lam Tin",
            "Tsing Yi Town",
            "Tsing Leng Tsui",
            "Ha Ko Tan",
            "Wong Uk",
            "Cheung Sha Wan",
            "Sha Tin Wai",
            "Yuen Chau Kok");

            var userCity = temp.sort();
        } else if(userCountry == "Hungary") {
            var temp = new Array("Budapest",
            "Debrecen",
            "Szeged",
            "Miskolc",
            "Pécs",
            "Győr",
            "Nyíregyháza",
            "Kecskemét",
            "Székesfehérvár",
            "Szombathely",
            "Szolnok",
            "Érd",
            "Tatabánya",
            "Sopron",
            "Kaposvár",
            "Veszprém",
            "Békéscsaba",
            "Zalaegerszeg",
            "Eger",
            "Nagykanizsa",
            "Dunaújváros",
            "Dunakeszi",
            "Hódmezővásárhely",
            "Szigetszentmiklós",
            "Vác",
            "Cegléd",
            "Baja",
            "Salgótarján",
            "Mosonmagyaróvár",
            "Ózd",
            "Gödöllő",
            "Szekszárd",
            "Hajdúböszörmény",
            "Pápa",
            "Gyöngyös",
            "Gyula",
            "Kiskunfélegyháza",
            "Budaörs",
            "Esztergom",
            "Ajka",
            "Orosháza",
            "Jászberény",
            "Szentes",
            "Kiskunhalas",
            "Szentendre",
            "Kazincbarcika",
            "Siófok",
            "Hajdúszoboszló",
            "Gyál",
            "Nagykőrös");

            var userCity = temp.sort();
        } else if(userCountry == "India") {
            var temp = new Array("Delhi",
            "Mumbai",
            "Kolkāta",
            "Bangalore",
            "Chennai",
            "Hyderābād",
            "Pune",
            "Ahmedabad",
            "Sūrat",
            "Lucknow",
            "Jaipur",
            "Cawnpore",
            "Mirzāpur",
            "Nāgpur",
            "Ghāziābād",
            "Indore",
            "Vadodara",
            "Vishākhapatnam",
            "Bhopāl",
            "Chinchvad",
            "Patna",
            "Ludhiāna",
            "Āgra",
            "Kalyān",
            "Madurai",
            "Jamshedpur",
            "Nāsik",
            "Farīdābād",
            "Aurangābād",
            "Rājkot",
            "Meerut",
            "Jabalpur",
            "Thāne",
            "Dhanbād",
            "Allahābād",
            "Vārānasi",
            "Srīnagar",
            "Amritsar",
            "Alīgarh",
            "Bhiwandi",
            "Gwalior",
            "Bhilai",
            "Hāora",
            "Rānchi",
            "Bezwāda",
            "Chandīgarh",
            "Mysore",
            "Raipur",
            "Kota",
            "Bareillycc");

            var userCity = temp.sort();
        } else if(userCountry == "Indonesia") {
            var temp = new Array("Jakarta",
            "Surabaya",
            "Bandung",
            "Bekasi",
            "Tangerang",
            "Medan",
            "Makassar",
            "Semarang",
            "Palembang",
            "Cilacap",
            "Bandar Lampung",
            "Padang",
            "Pekanbaru",
            "Denpasar",
            "Samarinda",
            "Banjarmasin",
            "Pontianak",
            "Serang",
            "Jambi",
            "Manado",
            "Kupang",
            "Yogyakarta",
            "Jayapura",
            "Mataram",
            "Ambon",
            "Bengkulu",
            "Palu",
            "Kendari",
            "Jember",
            "Majene",
            "Palangkaraya",
            "Banda Aceh",
            "Singaraja",
            "Tanjungpinang",
            "Martapura",
            "Gorontalo",
            "Prabumulih",
            "Banjar",
            "Pinrang",
            "Banyuwangi",
            "Gunungsitoli",
            "Pageralam",
            "Pangkalpinang",
            "Indramayu",
            "Pati",
            "Raba",
            "Maumere",
            "Biak",
            "Tomohon",
            "Sampit");

            var userCity = temp.sort();
        } else if(userCountry == "Italy") {
            var temp = new Array("Rome",
            "Milan",
            "Naples",
            "Turin",
            "Palermo",
            "Genoa",
            "Bologna",
            "Florence",
            "Bari",
            "Catania",
            "Venice",
            "Verona",
            "Messina",
            "Padova",
            "Trieste",
            "Taranto",
            "Brescia",
            "Parma",
            "Prato",
            "Modena",
            "Reggio di Calabria",
            "Reggio Emilia",
            "Perugia",
            "Ravenna",
            "Livorno",
            "Cagliari",
            "Foggia",
            "Rimini",
            "Salerno",
            "Ferrara",
            "Latina",
            "Giugliano in Campania",
            "Monza",
            "Siracusa",
            "Bergamo",
            "Pescara",
            "Trento",
            "Forlì",
            "Sassari",
            "Vicenza",
            "Terni",
            "Bolzano",
            "Novara",
            "Piacenza",
            "Ancona",
            "Andria",
            "Udine",
            "Arezzo",
            "Cesena",
            "Lecce");

            var userCity = temp.sort();
        } else if(userCountry == "Korea, Rep.") {
            var temp = new Array("Seoul",
            "Busan",
            "Incheon",
            "Daegu",
            "Gwangju",
            "Daejeon",
            "Suwon",
            "Ulsan",
            "Goyang",
            "Changwon",
            "Sŏngnam",
            "Bucheon",
            "Cheongju",
            "Hwasu-dong",
            "Jeonju",
            "Ansan",
            "Ch’?nan",
            "Yanggok",
            "Anyang",
            "Pohang",
            "Pyeongtaek",
            "Jeju",
            "Masan",
            "Uijeongbu",
            "Paju",
            "Gimpo",
            "Yeosu",
            "Chinju",
            "W?nju",
            "Asan",
            "Gwangmyeongni",
            "Iksan",
            "Yangsan",
            "Kunp’o",
            "Chuncheon",
            "Gyeongsan",
            "Kunsan",
            "Yeosu",
            "Suncheon",
            "Ky?ngju",
            "Mokpo",
            "Gangneung",
            "Osan",
            "Chungju",
            "Pocheon",
            "Andong",
            "Gwangyang",
            "Boryeong",
            "Sokcho",
            "Dongnae");

            var userCity = temp.sort();
        } else if(userCountry == "Malaysia") {
            var temp = new Array("Kuala Lumpur",
            "Klang",
            "Ipoh",
            "Butterworth",
            "Johor Bahru",
            "George Town",
            "Petaling Jaya",
            "Kuantan",
            "Shah Alam",
            "Kota Bharu",
            "Melaka",
            "Kota Kinabalu",
            "Seremban",
            "Sandakan",
            "Sungai Petani",
            "Kuching",
            "Kuala Terengganu",
            "Alor Setar",
            "Putrajaya",
            "Kangar",
            "Labuan",
            "Pasir Mas",
            "Tumpat",
            "Ketereh",
            "Kampung Lemal",
            "Pulai Chondong");

            var userCity = temp.sort();
        } else if(userCountry == "Mexico") {
            var temp = new Array("Mexico City",
            "Guadalajara",
            "Monterrey",
            "Tijuana",
            "Ecatepec",
            "Puebla",
            "León de los Aldama",
            "Juárez",
            "Zapopan",
            "Nezahualcóyotl",
            "Ciudad Nezahualcóyotl",
            "Mexicali",
            "Aguascalientes",
            "Mérida",
            "Chihuahua",
            "Naucalpan de Juárez",
            "San Luis Potosí",
            "Toluca",
            "Hermosillo",
            "Saltillo",
            "Querétaro",
            "Culiacán",
            "Morelia",
            "Tlalnepantla",
            "Cancún",
            "Tlajomulco de Zúñiga",
            "Reynosa",
            "Guadalupe",
            "Acapulco de Juárez",
            "Torreón",
            "Durango",
            "Villahermosa",
            "Chimalhuacán",
            "Tuxtla",
            "Tlaquepaque",
            "Veracruz",
            "Xalapa",
            "Ciudad Apodaca",
            "Ensenada",
            "Heroica Matamoros",
            "Cuautitlán Izcalli",
            "Mazatlán",
            "Mazatán",
            "Ixtapaluca",
            "Ciudad López Mateos",
            "Tultitlán de Mariano Escobedo",
            "San Nicolás de los Garza",
            "Celaya",
            "Ciudad Obregón",
            "Irapuato");

            var userCity = temp.sort();
        } else if(userCountry == "Myanmar") {
            var temp = new Array("Rangoon",
            "Mandalay",
            "Nay Pyi Taw",
            "Hpa-An",
            "Bago",
            "Myeik",
            "Mawlamyine",
            "Myitkyina",
            "Pathein",
            "Monywa",
            "Sittwe",
            "Hinthada",
            "Letpandan",
            "Myingyan",
            "Taunggyi",
            "Mudon",
            "Dawei",
            "Pyay",
            "Pakokku",
            "Magway",
            "Yenangyaung",
            "Taungoo",
            "Chauk",
            "Shwebo",
            "Pyapon",
            "Kengtung",
            "Sagaing",
            "Allanmyo",
            "Thongwa",
            "Ye",
            "Namtu",
            "Wakema",
            "Pyu",
            "Nyaungdon",
            "Amarapura",
            "Hakha",
            "Loikaw");

            var userCity = temp.sort();
        } else if(userCountry == "Netherlands") {
            var temp = new Array("The Hague",
            "Amsterdam",
            "Utrecht",
            "Rotterdam",
            "Eindhoven",
            "Almere",
            "Groningen",
            "Breda",
            "Apeldoorn",
            "Haarlem",
            "Zaanstad",
            "Arnhem",
            "’s-Hertogenbosch",
            "Leeuwarden",
            "Maastricht",
            "Zwolle",
            "Alphen aan den Rijn",
            "Emmen",
            "Delft",
            "Deventer",
            "Hilversum",
            "Heerlen",
            "Purmerend",
            "Lelystad",
            "Roosendaal",
            "Spijkenisse",
            "Ede",
            "Gouda",
            "Zaandam",
            "Bergen op Zoom",
            "Capelle aan den IJssel",
            "Veenendaal",
            "Katwijk",
            "Zeist",
            "Nieuwegein",
            "Assen",
            "Hardenberg",
            "Barneveld",
            "Roermond",
            "Heerhugowaard",
            "Oosterhout",
            "Den Helder",
            "Hoogeveen",
            "Kampen",
            "Woerden",
            "Houten",
            "Sittard",
            "IJmuiden",
            "Middelburg",
            "Harderwijk");

            var userCity = temp.sort();
        } else if(userCountry == "Poland") {
            var temp = new Array("Warsaw",
            "Kraków",
            "Łódź",
            "Wrocław",
            "Poznań",
            "Gdańsk",
            "Szczecin",
            "Bydgoszcz",
            "Lublin",
            "Białystok",
            "Katowice",
            "Gdynia",
            "Częstochowa",
            "Radom",
            "Toruń",
            "Sosnowiec",
            "Kielce",
            "Rzeszów",
            "Gliwice",
            "Zabrze",
            "Olsztyn",
            "Bielsko-Biała",
            "Bytom",
            "Rybnik",
            "Ruda Śląska",
            "Zielona Góra",
            "Tychy",
            "Opole",
            "Gorzów Wielkopolski",
            "Dąbrowa Górnicza",
            "Płock",
            "Elbląg",
            "Wałbrzych",
            "Chorzów",
            "Tarnów",
            "Koszalin",
            "Kalisz",
            "Legnica",
            "Włocławek",
            "Grudziądz",
            "Jaworzno",
            "Jelenia Góra",
            "Siedlce",
            "Mysłowice",
            "Piotrków Trybunalski",
            "Konin",
            "Inowrocław",
            "Ostrowiec Świętokrzyski",
            "Suwałki",
            "Gniezno");

            var userCity = temp.sort();
        } else if(userCountry == "Russian Federation") {
            var temp = new Array("Moscow",
            "Saint Petersburg",
            "Novosibirsk",
            "Yekaterinburg",
            "Nizhniy Novgorod",
            "Kazan",
            "Chelyabinsk",
            "Omsk",
            "Samara",
            "Rostov",
            "Ufa",
            "Krasnoyarsk",
            "Perm",
            "Voronezh",
            "Volgograd",
            "Krasnodar",
            "Saratov",
            "Tyumen",
            "Tolyatti",
            "Izhevsk",
            "Barnaul",
            "Ulyanovsk",
            "Irkutsk",
            "Khabarovsk",
            "Yaroslavl",
            "Vladivostok",
            "Makhachkala",
            "Tomsk",
            "Orenburg",
            "Kemerovo",
            "Novokuznetsk",
            "Ryazan",
            "Astrakhan",
            "Naberezhnyye Chelny",
            "Penza",
            "Lipetsk",
            "Kirov",
            "Cheboksary",
            "Tula",
            "Kaliningrad",
            "Balashikha",
            "Kursk",
            "Stavropol",
            "Ulan-Ude",
            "Tver",
            "Magnitogorsk",
            "Sochi",
            "Ivanovo",
            "Bryansk",
            "Belgorod");

            var userCity = temp.sort();
        } else if(userCountry == "Saudi Arabia") {
            var temp = new Array("Riyadh",
            "Jeddah",
            "Mecca",
            "Medina",
            "Ad Dammām",
            "Al Hufūf",
            "Buraydah",
            "Al Ḩillah",
            "Aţ Ţā’if",
            "Tabūk",
            "Khamīs Mushayţ",
            "Ḩā’il",
            "Al Qaţīf",
            "Al Mubarraz",
            "Al Kharj",
            "Najrān",
            "Yanbu‘",
            "Abhā",
            "Arar",
            "Jāzān",
            "Sakākā",
            "Al Bāḩah");

            var userCity = temp.sort();
        } else if(userCountry == "Singapore") {
            var temp = new Array("Singapore",
            "Keat Hong Village",
            "Choa Chu Kang New Town",
            "Bukit Panjang Estate",
            "Jalan Kayu",
            "Bukit Sembawang Estate",
            "Kampong Serangoon Kechil",
            "Kampong Cutforth",
            "Mok Peng Hiang Estate",
            "Woodlands New Town",
            "Kampong Pinang",
            "Serangoon",
            "Kampong Sungai Tengah",
            "Kampong Tongkang Pechah",
            "Kampong Teban",
            "Kangkar",
            "Jurong Town",
            "Kampong Ulu Jurong",
            "Seletar Hills Estate",
            "Tay Keng Loon Estate",
            "Matilda Estate",
            "Bukit Panjang New Town",
            "Kampong Beremban",
            "Marsiling",
            "Chia Keng",
            "Somapah Serangoon",
            "Jurong West",
            "Boon Lay",
            "Kampong Chai Chee",
            "Ulu Bedok",
            "Kampong Pachitan",
            "Bedok New Town",
            "Kampong Sireh",
            "Bedok Ville",
            "Kampong Bukit Panjang",
            "Kampong Lew Lian",
            "Marsiling Estate",
            "Yio Chu Kang Estate",
            "Yio Chu Kang",
            "Ang Mo Kio New Town",
            "Kampong Amoy Quee",
            "Singapore United Plantation",
            "Kampong Ladang",
            "Kampong Ubi",
            "Kampong Reteh",
            "Kampong Kebun Baharu",
            "Ong Lee",
            "Saint Michael’s Estate",
            "Teacher’s Housing Estate",
            "Saga");

            var userCity = temp.sort();
        } else if(userCountry == "Spain") {
            var temp = new Array("Madrid",
            "Barcelona",
            "Sevilla",
            "Málaga",
            "Valencia",
            "Zaragoza",
            "Palma",
            "Murcia",
            "Las Palmas",
            "A Coruña",
            "Bilbao",
            "Alicante",
            "Córdoba",
            "Valladolid",
            "Vigo",
            "Gijón",
            "Vitoria-Gasteiz",
            "Elche",
            "Granada",
            "Tarrasa",
            "Badalona",
            "Oviedo",
            "Petrel",
            "Sabadell",
            "Cartagena",
            "Jerez de la Frontera",
            "Santa Cruz",
            "Pamplona",
            "León",
            "Almería",
            "Logroño",
            "Fuenlabrada",
            "Leganés",
            "Donostia",
            "Mataró",
            "Albacete",
            "Castellón de la Plana",
            "Santander",
            "Getafe",
            "Alcorcón",
            "Burgos",
            "Guadalajara",
            "La Laguna",
            "Badajoz",
            "Marbella",
            "Salamanca",
            "Huelva",
            "Ciudad de Melilla",
            "Tarragona",
            "Dos Hermanas");

            var userCity = temp.sort();
        } else if(userCountry == "Thailand") {
            var temp = new Array("Bangkok",
            "Nonthaburi",
            "Pak Kret",
            "Hat Yai",
            "Nakhon Ratchasima",
            "Chiang Mai",
            "Surat Thani",
            "Udon Thani",
            "Ban Bang Pu Mai",
            "Khon Kaen",
            "Phatthaya",
            "Nakhon Si Thammarat",
            "Ban Mangkon",
            "Nakhon Sawan",
            "Ban Talat Rangsit",
            "Ubon Ratchathani",
            "Nakhon Pathom",
            "Phuket",
            "Phitsanulok",
            "Chiang Rai",
            "Ko Samui",
            "Ban Suan",
            "Songkhla",
            "Rayong",
            "Saraburi",
            "Yala",
            "Trang",
            "Samut Sakhon",
            "Ban Bang Kaeo",
            "Hua Hin",
            "Ban Rangsit",
            "Khlong Luang",
            "Lampang",
            "Prachuap Khiri Khan",
            "Sakon Nakhon",
            "Phra Nakhon Si Ayutthaya",
            "Maha Sarakham",
            "Muban Saeng Bua Thong",
            "Samut Prakan",
            "Bang Bua Thong",
            "Nong Khai",
            "Ban Plai Bua Phatthana",
            "Ban Bang Mae Nang",
            "Ban Pet",
            "Pattani",
            "Singhanakhon",
            "Si Sa Ket",
            "Bang Kruai",
            "Su-ngai Kolok",
            "Narathiwat");

            var userCity = temp.sort();
        } else if(userCountry == "Turkey") {
            var temp = new Array("Istanbul",
            "Ankara",
            "İzmir",
            "Bursa",
            "Antalya",
            "Konya",
            "Adana",
            "Gaziantep",
            "Şanlıurfa",
            "Mersin",
            "Diyarbakır",
            "Kayseri",
            "Samsun",
            "Tekirdağ",
            "Denizli",
            "Eskişehir",
            "Trabzon",
            "Erzurum",
            "Malatya",
            "Batman",
            "Kahramanmaraş",
            "Elazığ",
            "Hatay",
            "Sivas",
            "Kocaeli",
            "Van",
            "Tarsus",
            "Balıkesir",
            "Alanya",
            "Adıyaman",
            "Afyonkarahisar",
            "İskenderun",
            "Aksaray",
            "Çorum",
            "İnegöl",
            "Kütahya",
            "Osmaniye",
            "Çorlu",
            "Sakarya",
            "Isparta",
            "Kızıltepe",
            "Uşak",
            "Manisa",
            "Düzce",
            "Niğde",
            "Bolu",
            "Tokat",
            "Kırıkkale",
            "Viranşehir",
            "Karaman");

            var userCity = temp.sort();
        } else if(userCountry == "Ukraine") {
            var temp = new Array("Istanbul",
            "Ankara",
            "İzmir",
            "Bursa",
            "Antalya",
            "Konya",
            "Adana",
            "Gaziantep",
            "Şanlıurfa",
            "Mersin",
            "Diyarbakır",
            "Kayseri",
            "Samsun",
            "Tekirdağ",
            "Denizli",
            "Eskişehir",
            "Trabzon",
            "Erzurum",
            "Malatya",
            "Batman",
            "Kahramanmaraş",
            "Elazığ",
            "Hatay",
            "Sivas",
            "Kocaeli",
            "Van",
            "Tarsus",
            "Balıkesir",
            "Alanya",
            "Adıyaman",
            "Afyonkarahisar",
            "İskenderun",
            "Aksaray",
            "Çorum",
            "İnegöl",
            "Kütahya",
            "Osmaniye",
            "Çorlu",
            "Sakarya",
            "Isparta",
            "Kızıltepe",
            "Uşak",
            "Manisa",
            "Düzce",
            "Niğde",
            "Bolu",
            "Tokat",
            "Kırıkkale",
            "Viranşehir",
            "Karaman");

            var userCity = temp.sort();
        } else if(userCountry == "United Kingdom") {
            var temp = new Array("London",
            "Birmingham",
            "Manchester",
            "Leeds",
            "Newcastle",
            "Birstall",
            "Glasgow",
            "Liverpool",
            "Portsmouth",
            "Southampton",
            "Nottingham",
            "Bristol",
            "Sheffield",
            "Kingston upon Hull",
            "Leicester",
            "Edinburgh",
            "Caerdydd",
            "Stoke-on-Trent",
            "Coventry",
            "Reading",
            "Belfast",
            "Derby",
            "Plymouth",
            "Wolverhampton",
            "Abertawe",
            "Milton Keynes",
            "Aberdeen",
            "Norwich",
            "Luton",
            "Islington",
            "Swindon",
            "Croydon",
            "Basildon",
            "Bournemouth",
            "Worthing",
            "Ipswich",
            "Middlesbrough",
            "Sunderland",
            "Ilford",
            "Warrington",
            "Slough",
            "Huddersfield",
            "Oxford",
            "York",
            "Poole",
            "Harrow",
            "Dundee",
            "Saint Albans",
            "Telford",
            "Blackpool");

            var userCity = temp.sort();
        } else if(userCountry == "United States") {
            var temp = new Array("New York",
            "Los Angeles",
            "Chicago",
            "Miami",
            "Dallas",
            "Philadelphia",
            "Houston",
            "Atlanta",
            "Washington",
            "Boston",
            "Phoenix",
            "Seattle",
            "San Francisco",
            "Detroit",
            "San Diego",
            "Minneapolis",
            "Tampa",
            "Denver",
            "Brooklyn",
            "Queens",
            "Riverside",
            "Baltimore",
            "Las Vegas",
            "Portland",
            "San Antonio",
            "St. Louis",
            "Sacramento",
            "Orlando",
            "San Jose",
            "Cleveland",
            "Pittsburgh",
            "Austin",
            "Cincinnati",
            "Kansas City",
            "Manhattan",
            "Indianapolis",
            "Columbus",
            "Charlotte",
            "Virginia Beach",
            "Bronx",
            "Milwaukee",
            "Providence",
            "Jacksonville",
            "Salt Lake City",
            "Nashville",
            "Richmond",
            "Memphis",
            "Raleigh",
            "New Orleans",
            "Louisville");

            var userCity = temp.sort();
        }

        $("#userCity").find('option').remove();
        for(i=0; i < userCity.length; i++){
            $("#userCity").append('<option value="'+userCity [i]+'">'+userCity [i]+'</option>');
        }
    });
});